apiVersion: apps/v1
kind: Deployment
metadata:
  name: q0717
spec:
  replicas: 1
  selector:
    matchLabels:
      app: q0717
  template:
    metadata:
      labels:
        app: q0717
    spec:
      containers:
      - image: okteto.dev/q0717:latest
        name: q0717
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ea49d4d8-f127-4c69-a311-82e96afa7bc0"
        - name: Vless_Path
          value: "/l555"
        - name: Vmess_UUID
          value: "ea49d4d8-f127-4c69-a311-82e96afa7bc0"
        - name: Vmess_Path
          value: "/m555"
        - name: Share_Path
          value: "/v2link"
